// FULL CODE SNIPPET: middleware/uploadMiddleware.js

const multer = require('multer');
// Assuming AppError is in ../utils/ relative to the middleware folder
const AppError = require('../utils/appError');

// --- Multer Storage Configuration ---
// We use memoryStorage because we're going to immediately process the image buffer
// (e.g., upload to Cloudinary) rather than saving it to the server's disk first.
const multerStorage = multer.memoryStorage();

// --- Multer File Filter Configuration ---
// This function checks the mimetype of the uploaded file to ensure it's an image.
const multerFilter = (req, file, cb) => {
    // Check if the mimetype starts with 'image/' (e.g., 'image/jpeg', 'image/png')
    if (file.mimetype.startsWith('image')) {
        cb(null, true); // Accept the file (first argument null = no error)
    } else {
        // Reject the file if it's not an image
        // Create an AppError (our custom error class) to be handled by global error handler
        cb(new AppError('Not an image! Please upload only image files.', 400), false); // Pass error and false (don't accept)
    }
};

// --- Multer Upload Configuration ---
// Create the Multer instance with the defined storage and filter.
const upload = multer({
    storage: multerStorage,
    fileFilter: multerFilter,
    limits: {
        // Set a file size limit (e.g., 5 Megabytes)
        fileSize: 5 * 1024 * 1024 // 5MB in bytes
    }
});

// --- Export Middleware ---
// Export the middleware function generated by multer for handling a single file upload.
// 'profileImage' is the name of the field in the incoming form data (FormData)
// that will contain the file. This name MUST match the name used in the frontend form.
// This middleware will add a 'file' object to the `req` object (i.e., req.file)
// if a valid file is uploaded, or it will pass an error if filtering/limits fail.
exports.uploadPersonPhoto = upload.single('profileImage');


// --- Optional Resize Middleware Placeholder ---
// If you wanted to resize images on the server *before* uploading to Cloudinary,
// you would use a library like 'sharp' here. This middleware would run AFTER
// uploadPersonPhoto and modify req.file.buffer.
/*
const sharp = require('sharp');

exports.resizePersonPhoto = async (req, res, next) => {
    // If no file was uploaded in the previous step, just continue
    if (!req.file) return next();

    try {
        // Example: Resize to 300x300, convert to jpeg
        req.file.buffer = await sharp(req.file.buffer)
            .resize(300, 300)
            .toFormat('jpeg')
            .jpeg({ quality: 90 }) // Set JPEG quality
            .toBuffer();

        console.log('Image resized successfully.');
        next(); // Proceed to the next middleware (e.g., the update controller)
    } catch (err) {
        console.error("Image resizing error:", err);
        // Pass error to global error handler
        next(new AppError('Failed to process image.', 500));
    }
};
*/